INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (60, 'Душка от кровати', 2, 2, 45, 0, 500);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (61, 'Нож', 1, 0, 35, 0, 350);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (62, 'Стул', 2, 3, 27, 0, 300);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (63, 'Швабра', 2, 4, 25, 0, 260);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (64, 'Веревка', 2, 0, 20, 0, 150);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (65, 'Шприц', 1, 0, 16, 1, 100);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (66, 'Ключ', 1, 0, 12, 0, 60);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (67, 'Вилка', 1, 0, 9, 0, 45);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (68, 'Мебельный гвоздь', 1, 0, 6, 0, 25);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (69, 'Ручка', 1, 0, 4, 0, 15);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (70, 'Дуршлаг', 8, 9, 2, 0, 200);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (71, 'Ложка', 1, 0, 1, 0, 2);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (72, 'Бахилы медицинские', 5, 1, 0, 1, 10);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (73, 'Бинты на ноги', 5, 1, 0, 0, 1);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (74, 'Бинты на руки', 4, 1, 0, 1, 4);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (75, 'Кепка', 8, 5, 0, 0, 50);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (76, 'Комбинезон', 7, 11, 0, 0, 250);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (77, 'Медицинская шапка', 8, 3, 0, 1, 15);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (78, 'Перчатки медицинские', 4, 3, 0, 1, 30);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (79, 'Порванная на лоскуты простыня', 4, 2, 0, 0, 10);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (80, 'Простыня', 7, 3, 0, 0, 20);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (81, 'Упаковка из-под еды', 4, 1, 0, 0, 2);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (82, 'Футболка', 7, 6, 0, 0, 65);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (83, 'Халат', 7, 5, 0, 1, 70);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (84, 'Шапка из бинтов', 8, 2, 0, 0, 6);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (85, 'Шорты', 6, 5, 0, 0, 60);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (86, 'Штаны врача', 6, 8, 0, 2, 200);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (87, 'Трусы', 6, 1, 0, 0, 2);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (88, 'Большая упаковка из-под еды', 5, 2, -1, 0, 5);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (89, 'Смирительная рубашка', 7, 12, -5, 2, 200);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (90, 'Перчатки зимние', 4, 5, 0, 0, 70);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (91, 'Варежки', 4, 7, 0, 0, 150);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (92, 'Кроссовки', 5, 8, 0, 0, 160);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (93, 'Ботинки', 5, 10, 0, 0, 220);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (94, 'Носки', 5, 3, 0, 0, 30);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (95, 'Сандали', 5, 6, 0, 0, 80);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (96, 'Штаны', 6, 8, 0, 0, 160);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (97, 'Синтепоновые штаны', 6, 12, 0, 0, 350);
INSERT INTO public."Items" (id, "itemName", category_id, pz, pa, py, cost) VALUES (98, 'Спортивные штаны', 6, 3, 0, 0, 35);